# Generated by Django 6.0.7 on 2026-07-31 03:30

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        TrigramExtension(),
    ]
