# Generated by Django 6.0.7 on 2026-08-03 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_forma_laboratorio_paishabilitacionproducto_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariobusqueda',
            name='producto',
            field=models.ForeignKey(blank=True, db_column='cod_producto', null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.productos'),
        ),
        migrations.AlterField(
            model_name='usuariobusqueda',
            name='medico',
            field=models.ForeignKey(blank=True, db_column='nro_medico', null=True, on_delete=django.db.models.deletion.CASCADE, to='personas.medico'),
        ),
    ]
