# Generated by Django 6.0.7 on 2026-08-03 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_usuariobusqueda_producto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forma',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='laboratorio',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='paishabilitacionproducto',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'managed': True},
        ),
    ]
