# Generated by Django 6.0.7 on 2026-08-03 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_alter_forma_options_alter_laboratorio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forma',
            options={},
        ),
        migrations.AlterModelOptions(
            name='laboratorio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paishabilitacionproducto',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
        migrations.AddField(
            model_name='medico',
            name='causa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='cdg_region',
            field=models.ForeignKey(blank=True, db_column='cdg_region', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.region'),
        ),
        migrations.AddField(
            model_name='pais',
            name='abr_pais',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='paishabilitacionproducto',
            name='cod_producto',
            field=models.ForeignKey(blank=True, db_column='cod_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.productos'),
        ),
        migrations.AddField(
            model_name='paishabilitacionproducto',
            name='id_pais',
            field=models.ForeignKey(blank=True, db_column='id_pais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.pais'),
        ),
        migrations.AddField(
            model_name='productos',
            name='desc_ext',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='id_forma',
            field=models.ForeignKey(blank=True, db_column='id_forma', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.forma'),
        ),
        migrations.AddField(
            model_name='productos',
            name='id_labo',
            field=models.ForeignKey(blank=True, db_column='id_labo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.laboratorio'),
        ),
        migrations.AddField(
            model_name='productos',
            name='paises_habilitados',
            field=models.ManyToManyField(through='personas.PaisHabilitacionProducto', to='personas.pais'),
        ),
        migrations.AddField(
            model_name='region',
            name='id_pais',
            field=models.ForeignKey(blank=True, db_column='id_pais', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='personas.pais'),
        ),
    ]
